name: Test and Build Containers

on:
  push:
    branches:
      - main
    tags:
      - "**"
  workflow_dispatch:
  pull_request:

permissions:
  packages: write
  contents: write
  id-token: write
  attestations: write

jobs:
  test:
    name: Run Python Tests
    uses: taranis-ai/github-actions/.github/workflows/python-uv.yml@master

  build_container:
    name: Build and Push Containers
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    uses: taranis-ai/github-actions/.github/workflows/build-multiarch-bot-container.yml@master
    with:
      ghcr_image: ghcr.io/taranis-ai/taranis-base-bot
      model: base
      os: ${{ matrix.os }}

  merge_container:
    name: Merge Container Manifests
    needs: build_container
    strategy:
      fail-fast: false
    uses: taranis-ai/github-actions/.github/workflows/merge-multiarch-bot-container.yml@master
    with:
      ghcr_image: ghcr.io/taranis-ai/taranis-base-bot
      model: base
      latest: true
